{ Askr.Urd.Query — typed queries.

  This is the part the PRD itself calls the weakest in the design, and the
  part that decides whether the premise holds. Pascal has no __callStatic,
  so Eloquent's Customer::where(...) does not exist. In return, typed
  columns give something Eloquent has never managed: a compile error on a
  typo and on a wrong value type.

      Query<TCustomer>
        .Where(Customers.Balance, GT, 0)
        .Where(Customers.Email, Like, '%@gets.no')
        .OrderBy(Customers.CreatedAt, Desc)
        .Limit(50)
        .Get;

  .Where(Customers.Balance, GT, 'abc') does not compile.

  The mechanism: TCol<T> is a generic record, and specialisations of it
  are distinct types. Where is overloaded on each of them, with the value
  type following. That is how Free Pascal manages this without generic
  methods — which the compiler does not allow inside a generic class
  anyway.

  Two departures from the PRD, both forced by Free Pascal 3.2.2:

    * Eager loading is called Preload, not With. With is a reserved word.
    * The entry point is TQuery<TCustomer>.New, not Query<TCustomer>. A
      generic free function cannot be exported from a unit in 3.2.2: the
      declaration and the implementation get different mangled names for
      the type parameter, and variations on that make the compiler crash.
      The same goes for a generic class method on a non-generic class. If
      it works on trunk, Query<TCustomer> is one rename away. }
unit Askr.Urd.Query;

{$mode Delphi}{$H+}
{$POINTERMATH ON}

interface

uses
  SysUtils, TypInfo,
  Askr.Core.Arena, Askr.Core.Text, Askr.Core.Clock,
  Askr.Urd.Driver, Askr.Urd.Model;

type
  { Generated by Norn in step 3. Until then these are written by hand. }
  TCol<T> = record
    Name: ShortString;
    Table: ShortString;
  end;

  { The typed way to name a hidden column.

    A class helper, because TJsonHidden is declared with the model and the
    typed column is declared here -- the same arrangement as
    `Req.FillInto`, and for the same reason: a dependency the other way
    would make every model drag the query builder in.

    Six overloads that do one thing. The types are the point: a column
    that is not on this model, or that has been renamed since, does not
    compile. }
  TJsonHiddenHelper = class helper for TJsonHidden
    procedure Add(const C: TCol<Int64>); overload;
    procedure Add(const C: TCol<string>); overload;
    procedure Add(const C: TCol<Currency>); overload;
    procedure Add(const C: TCol<Double>); overload;
    procedure Add(const C: TCol<Boolean>); overload;
    procedure Add(const C: TCol<TDateTime>); overload;
  end;

  TColInt64 = TCol<Int64>;
  TColStr = TCol<string>;
  TColCurrency = TCol<Currency>;
  TColFloat = TCol<Double>;
  TColBool = TCol<Boolean>;
  TColDateTime = TCol<TDateTime>;

  { The names are short because they sit in the middle of a query and read
    as operators. }
  TSqlOp = (Eq, Ne, GT, GTE, LT, LTE, Like, ILike);
  TSqlDir = (Asc, Desc);

  EQueryError = class(EDbError);

  PWhereTerm = ^TWhereTerm;
  TWhereTerm = record
    Table: ShortString;
    Column: ShortString;
    Op: TSqlOp;
    Param: TDbParam;
    { Null-sjekk har ingen parameter. }
    NullCheck: Boolean;
    WantNull: Boolean;
    { IN-liste: ParamFirst..ParamFirst+ParamCount-1 i FInParams. }
    InList: Boolean;
    ParamFirst: Integer;
    ParamCount: Integer;
    { Bound with OR to the clause before it rather than AND. A group of
      these is parenthesised when built, so the precedence comes out as
      `a = 1 AND (b ILIKE x OR c ILIKE x)` and not something else. }
    OrPrev: Boolean;
  end;

  POrderTerm = ^TOrderTerm;
  TOrderTerm = record
    Table: ShortString;
    Column: ShortString;
    Dir: TSqlDir;
  end;

  { Inherits Count, Item and IsEmpty from TModelListBase, so serialisation
    and eager loading can work with the list without knowing M. }
  TModelList<M: TModel> = class(TModelListBase)
  private
    function GetItem(Index: Integer): M;
  public
    procedure Add(AItem: M);
    function First: M;
    property Items[Index: Integer]: M read GetItem; default;
  end;

  TQuery<M: TModel> = class(TArenaObject)
  private
    FModelClass: TModelClass;
    FMeta: TModelMeta;
    FConn: TDbConnection;
    FWheres: PWhereTerm;
    FWhereCount: Integer;
    FWhereCapacity: Integer;
    FOrders: POrderTerm;
    FOrderCount: Integer;
    FOrderCapacity: Integer;
    FInParams: PDbParam;
    FInCount: Integer;
    FInCapacity: Integer;
    FPreloads: array of string;
    FLimit: Integer;
    FOffset: Integer;
    FTrashed: (tsWithout, tsWith, tsOnly);
    function AddWhere: PWhereTerm;
    function AddOrder: POrderTerm;
    function AddInParam(const P: TDbParam): Integer;
    function SoftDeleteClause(out Only: Boolean): Boolean;
    function SoftDeleteAll: Int64;
    procedure BuildWhere(var B: TStrBuilder; var ParamNo: Integer;
      var Params: TArray<TDbParam>);
    procedure BuildTail(var B: TStrBuilder);
    function Conn: TDbConnection;
    procedure LoadRelation(List: TModelList<M>; const RelName: string);
  public
    constructor Create(AModelClass: TModelClass; AConn: TDbConnection = nil);

    { The entry point:  TQuery<TCustomer>.New.Where(...).Get

      The PRD writes Query<TCustomer>. That form needs a generic free
      function exported from a unit, and Free Pascal 3.2.2 cannot do it —
      see the comment at the bottom of this file. The class method gives
      the same type safety and four more characters to type. }
    class function New: TQuery<M>;
    { The same, against a particular connection rather than the ambient
      one. }
    class function Using(AConn: TDbConnection): TQuery<M>;

    { Soft-deleted rows are left out by default. That is the whole point of
      soft deletes: a forgotten `WHERE deleted_at IS NULL` is exactly the
      mistake the mechanism exists to make impossible.

      WithTrashed includes them, OnlyTrashed shows only them. On a model
      without SoftDeletes both do nothing. }
    function WithTrashed: TQuery<M>;
    function OnlyTrashed: TQuery<M>;

    function Where(const Col: TColInt64; Op: TSqlOp; Value: Int64): TQuery<M>; overload;
    function Where(const Col: TColStr; Op: TSqlOp; const Value: string): TQuery<M>; overload;
    function Where(const Col: TColCurrency; Op: TSqlOp; Value: Currency): TQuery<M>; overload;
    function Where(const Col: TColFloat; Op: TSqlOp; Value: Double): TQuery<M>; overload;
    function Where(const Col: TColBool; Op: TSqlOp; Value: Boolean): TQuery<M>; overload;
    function Where(const Col: TColDateTime; Op: TSqlOp; Value: TDateTime): TQuery<M>; overload;

    { Free-text search across several columns: one expression, OR between
      the columns.

      Without this TQuery has only AND, and "find Ada in the name or the
      email" cannot be expressed. It is deliberately narrow — one
      operator, one expression, no nesting — because a general grouping
      language is a bigger question than a list needs. Empty text or an
      empty column list adds no clause at all. }
    function WhereAnyLike(const Cols: array of TColStr;
      const Text: string; CaseSensitive: Boolean = False): TQuery<M>;

    function WhereIn(const Col: TColInt64; const Values: array of Int64): TQuery<M>; overload;
    function WhereIn(const Col: TColStr; const Values: array of string): TQuery<M>; overload;

    function WhereNull(const Col: TColInt64): TQuery<M>; overload;
    function WhereNull(const Col: TColStr): TQuery<M>; overload;
    function WhereNull(const Col: TColCurrency): TQuery<M>; overload;
    function WhereNull(const Col: TColDateTime): TQuery<M>; overload;
    function WhereNotNull(const Col: TColInt64): TQuery<M>; overload;
    function WhereNotNull(const Col: TColStr): TQuery<M>; overload;
    function WhereNotNull(const Col: TColCurrency): TQuery<M>; overload;
    function WhereNotNull(const Col: TColDateTime): TQuery<M>; overload;

    function OrderBy(const Col: TColInt64; Dir: TSqlDir = Asc): TQuery<M>; overload;
    function OrderBy(const Col: TColStr; Dir: TSqlDir = Asc): TQuery<M>; overload;
    function OrderBy(const Col: TColCurrency; Dir: TSqlDir = Asc): TQuery<M>; overload;
    function OrderBy(const Col: TColFloat; Dir: TSqlDir = Asc): TQuery<M>; overload;
    function OrderBy(const Col: TColDateTime; Dir: TSqlDir = Asc): TQuery<M>; overload;

    function Limit(N: Integer): TQuery<M>;
    function Offset(N: Integer): TQuery<M>;

    { Eager loading. Not called With, because with is a reserved word. }
    function Preload(const Relations: array of string): TQuery<M>;

    function Get: TModelList<M>;
    function First: M;
    function Find(Id: Int64): M;
    function Count: Int64;
    function Paginate(Page, PerPage: Integer): TModelList<M>;
    { Sletter alt som matcher. Returnerer antall rader. }
    { With SoftDeletes this sets deleted_at, as Model.Delete does.
      ForceDeleteAll deletes regardless. RestoreAll brings the
      soft-deleted ones back. }
    function DeleteAll: Int64;
    function ForceDeleteAll: Int64;
    function RestoreAll: Int64;

    { The SQL the query would run. For debugging, and for tests that do not
      want a database. }
    function ToSql: string;
  end;

{ Lives in the interface because generic methods in FPC 3.2.2 may not
  reference symbols that exist only in the implementation section. }
function OpText(Op: TSqlOp; Dialect: TSqlDialect): string;

{ A helper for writing column constants by hand until Norn generates
  them. }
function ColInt64(const ATable, AName: string): TColInt64;
function ColStr(const ATable, AName: string): TColStr;
function ColCurrency(const ATable, AName: string): TColCurrency;
function ColFloat(const ATable, AName: string): TColFloat;
function ColBool(const ATable, AName: string): TColBool;
function ColDateTime(const ATable, AName: string): TColDateTime;

{ Preload for a BelongsToMany. In the interface only because a generic
  method may not call a routine the unit keeps to itself: TQuery<M> is
  specialised in the caller's unit, and from there the call has to
  resolve. Not meant to be called directly. }
procedure LoadManyToMany(List: TModelListBase; Meta: TModelMeta;
  const Rel: TRelationInfo; C: TDbConnection; A: TArena);

implementation

procedure TJsonHiddenHelper.Add(const C: TCol<Int64>);
begin
  AddColumn(string(C.Name));
end;

procedure TJsonHiddenHelper.Add(const C: TCol<string>);
begin
  AddColumn(string(C.Name));
end;

procedure TJsonHiddenHelper.Add(const C: TCol<Currency>);
begin
  AddColumn(string(C.Name));
end;

procedure TJsonHiddenHelper.Add(const C: TCol<Double>);
begin
  AddColumn(string(C.Name));
end;

procedure TJsonHiddenHelper.Add(const C: TCol<Boolean>);
begin
  AddColumn(string(C.Name));
end;

procedure TJsonHiddenHelper.Add(const C: TCol<TDateTime>);
begin
  AddColumn(string(C.Name));
end;

function ColInt64(const ATable, AName: string): TColInt64;
begin
  Result.Table := ATable;
  Result.Name := AName;
end;

function ColStr(const ATable, AName: string): TColStr;
begin
  Result.Table := ATable;
  Result.Name := AName;
end;

function ColCurrency(const ATable, AName: string): TColCurrency;
begin
  Result.Table := ATable;
  Result.Name := AName;
end;

function ColFloat(const ATable, AName: string): TColFloat;
begin
  Result.Table := ATable;
  Result.Name := AName;
end;

function ColBool(const ATable, AName: string): TColBool;
begin
  Result.Table := ATable;
  Result.Name := AName;
end;

function ColDateTime(const ATable, AName: string): TColDateTime;
begin
  Result.Table := ATable;
  Result.Name := AName;
end;

{ ILIKE exists only in Postgres.

  In MySQL and SQLite, LIKE is already case-insensitive — in MySQL because
  the collation is (utf8mb4 with ai_ci, which is the default), in SQLite
  because the built-in LIKE is, for ASCII. That last one is worth knowing:
  SQLite still separates "é" from "É", because ICU is not part of the
  ordinary build. It is a real difference between the dialects, and it
  should be written down rather than discovered.

  Before this, ILIKE was sent verbatim to all three, and a query with
  ILike against SQLite failed with 'near "ILIKE": syntax error'. }
function OpText(Op: TSqlOp; Dialect: TSqlDialect): string;
begin
  case Op of
    Eq:    Result := ' = ';
    Ne:    Result := ' <> ';
    GT:    Result := ' > ';
    GTE:   Result := ' >= ';
    LT:    Result := ' < ';
    LTE:   Result := ' <= ';
    Like:  Result := ' LIKE ';
    ILike:
      if Dialect = sdPostgres then
        Result := ' ILIKE '
      else
        Result := ' LIKE ';
  end;
  { Ingen else: alle TSqlOp er dekket. Se kommentaren i Askr.Urd.Model. }
end;

{ TModelList<M> }

procedure TModelList<M>.Add(AItem: M);
begin
  AddPointer(Pointer(AItem));
end;

function TModelList<M>.GetItem(Index: Integer): M;
begin
  if (Index < 0) or (Index >= Count) then
    raise EQueryError.CreateFmt('Indeks %d utenfor 0..%d', [Index, Count - 1]);
  Result := M(Item(Index));
end;

function TModelList<M>.First: M;
begin
  Result := M(Item(0));
end;

{ TQuery<M> }

constructor TQuery<M>.Create(AModelClass: TModelClass; AConn: TDbConnection);
begin
  inherited Create;
  FModelClass := AModelClass;
  FMeta := AModelClass.Meta;
  FConn := AConn;
  FLimit := -1;
  FOffset := -1;
end;

function TQuery<M>.Conn: TDbConnection;
begin
  if FConn <> nil then
    Exit(FConn);
  Result := CurrentDb;
  if Result = nil then
    raise EQueryError.Create(
      'No database connection. Pass one to Query, or set the ambient ' +
      'one with UseDb.');
end;

function TQuery<M>.AddWhere: PWhereTerm;
var
  NewCap: Integer;
  NewPtr: PWhereTerm;
begin
  if FWhereCount >= FWhereCapacity then
  begin
    if FWhereCapacity = 0 then
      NewCap := 8
    else
      NewCap := FWhereCapacity * 2;
    NewPtr := PWhereTerm(Arena.AllocZero(PtrUInt(NewCap) * SizeOf(TWhereTerm)));
    if FWhereCount > 0 then
      Move(FWheres^, NewPtr^, PtrUInt(FWhereCount) * SizeOf(TWhereTerm));
    FWheres := NewPtr;
    FWhereCapacity := NewCap;
  end;
  Result := FWheres + FWhereCount;
  Inc(FWhereCount);
end;

function TQuery<M>.AddOrder: POrderTerm;
var
  NewCap: Integer;
  NewPtr: POrderTerm;
begin
  if FOrderCount >= FOrderCapacity then
  begin
    if FOrderCapacity = 0 then
      NewCap := 4
    else
      NewCap := FOrderCapacity * 2;
    NewPtr := POrderTerm(Arena.AllocZero(PtrUInt(NewCap) * SizeOf(TOrderTerm)));
    if FOrderCount > 0 then
      Move(FOrders^, NewPtr^, PtrUInt(FOrderCount) * SizeOf(TOrderTerm));
    FOrders := NewPtr;
    FOrderCapacity := NewCap;
  end;
  Result := FOrders + FOrderCount;
  Inc(FOrderCount);
end;

function TQuery<M>.AddInParam(const P: TDbParam): Integer;
var
  NewCap: Integer;
  NewPtr: PDbParam;
begin
  if FInCount >= FInCapacity then
  begin
    if FInCapacity = 0 then
      NewCap := 16
    else
      NewCap := FInCapacity * 2;
    NewPtr := PDbParam(Arena.AllocZero(PtrUInt(NewCap) * SizeOf(TDbParam)));
    if FInCount > 0 then
      Move(FInParams^, NewPtr^, PtrUInt(FInCount) * SizeOf(TDbParam));
    FInParams := NewPtr;
    FInCapacity := NewCap;
  end;
  FInParams[FInCount] := P;
  Result := FInCount;
  Inc(FInCount);
end;

function TQuery<M>.Where(const Col: TColInt64; Op: TSqlOp; Value: Int64): TQuery<M>;
var
  W: PWhereTerm;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.Op := Op;
  W^.Param := DbParam(Arena, Value);
  Result := Self;
end;

function TQuery<M>.Where(const Col: TColStr; Op: TSqlOp; const Value: string): TQuery<M>;
var
  W: PWhereTerm;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.Op := Op;
  W^.Param := DbParam(Arena, Value);
  Result := Self;
end;

function TQuery<M>.Where(const Col: TColCurrency; Op: TSqlOp; Value: Currency): TQuery<M>;
var
  W: PWhereTerm;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.Op := Op;
  W^.Param := DbParam(Arena, Value);
  Result := Self;
end;

function TQuery<M>.Where(const Col: TColFloat; Op: TSqlOp; Value: Double): TQuery<M>;
var
  W: PWhereTerm;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.Op := Op;
  W^.Param := DbParam(Arena, FloatToSql(Value));
  Result := Self;
end;

function TQuery<M>.Where(const Col: TColBool; Op: TSqlOp; Value: Boolean): TQuery<M>;
var
  W: PWhereTerm;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.Op := Op;
  W^.Param := DbParam(Arena, Value);
  Result := Self;
end;

function TQuery<M>.Where(const Col: TColDateTime; Op: TSqlOp; Value: TDateTime): TQuery<M>;
var
  W: PWhereTerm;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.Op := Op;
  W^.Param := DbParamDateTime(Arena, Value);
  Result := Self;
end;

function TQuery<M>.WhereAnyLike(const Cols: array of TColStr;
  const Text: string; CaseSensitive: Boolean): TQuery<M>;
var
  I: Integer;
  W: PWhereTerm;
  Op: TSqlOp;
  Pattern_: string;
begin
  Result := Self;
  if (Length(Cols) = 0) or (Text = '') then
    Exit;

  if CaseSensitive then
    Op := Like
  else
    Op := ILike;
  Pattern_ := '%' + Text + '%';

  for I := 0 to High(Cols) do
  begin
    W := AddWhere;
    W^.Table := Cols[I].Table;
    W^.Column := Cols[I].Name;
    W^.Op := Op;
    W^.Param := DbParam(Arena, Pattern_);
    { The first clause in the group binds as usual to what came before;
      the rest with OR. The parenthesis is added when building. }
    W^.OrPrev := I > 0;
  end;
end;

function TQuery<M>.WhereIn(const Col: TColInt64; const Values: array of Int64): TQuery<M>;
var
  W: PWhereTerm;
  I, First_: Integer;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.InList := True;
  First_ := FInCount;
  for I := 0 to High(Values) do
    AddInParam(DbParam(Arena, Values[I]));
  W^.ParamFirst := First_;
  W^.ParamCount := Length(Values);
  Result := Self;
end;

function TQuery<M>.WhereIn(const Col: TColStr; const Values: array of string): TQuery<M>;
var
  W: PWhereTerm;
  I, First_: Integer;
begin
  W := AddWhere;
  W^.Table := Col.Table;
  W^.Column := Col.Name;
  W^.InList := True;
  First_ := FInCount;
  for I := 0 to High(Values) do
    AddInParam(DbParam(Arena, Values[I]));
  W^.ParamFirst := First_;
  W^.ParamCount := Length(Values);
  Result := Self;
end;

function TQuery<M>.WhereNull(const Col: TColInt64): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; W^.WantNull := True; Result := Self;
end;

function TQuery<M>.WhereNull(const Col: TColStr): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; W^.WantNull := True; Result := Self;
end;

function TQuery<M>.WhereNull(const Col: TColCurrency): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; W^.WantNull := True; Result := Self;
end;

function TQuery<M>.WhereNull(const Col: TColDateTime): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; W^.WantNull := True; Result := Self;
end;

function TQuery<M>.WhereNotNull(const Col: TColInt64): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; Result := Self;
end;

function TQuery<M>.WhereNotNull(const Col: TColStr): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; Result := Self;
end;

function TQuery<M>.WhereNotNull(const Col: TColCurrency): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; Result := Self;
end;

function TQuery<M>.WhereNotNull(const Col: TColDateTime): TQuery<M>;
var W: PWhereTerm;
begin
  W := AddWhere; W^.Table := Col.Table; W^.Column := Col.Name;
  W^.NullCheck := True; Result := Self;
end;

function TQuery<M>.OrderBy(const Col: TColInt64; Dir: TSqlDir): TQuery<M>;
var O: POrderTerm;
begin
  O := AddOrder; O^.Table := Col.Table; O^.Column := Col.Name; O^.Dir := Dir;
  Result := Self;
end;

function TQuery<M>.OrderBy(const Col: TColStr; Dir: TSqlDir): TQuery<M>;
var O: POrderTerm;
begin
  O := AddOrder; O^.Table := Col.Table; O^.Column := Col.Name; O^.Dir := Dir;
  Result := Self;
end;

function TQuery<M>.OrderBy(const Col: TColCurrency; Dir: TSqlDir): TQuery<M>;
var O: POrderTerm;
begin
  O := AddOrder; O^.Table := Col.Table; O^.Column := Col.Name; O^.Dir := Dir;
  Result := Self;
end;

function TQuery<M>.OrderBy(const Col: TColFloat; Dir: TSqlDir): TQuery<M>;
var O: POrderTerm;
begin
  O := AddOrder; O^.Table := Col.Table; O^.Column := Col.Name; O^.Dir := Dir;
  Result := Self;
end;

function TQuery<M>.OrderBy(const Col: TColDateTime; Dir: TSqlDir): TQuery<M>;
var O: POrderTerm;
begin
  O := AddOrder; O^.Table := Col.Table; O^.Column := Col.Name; O^.Dir := Dir;
  Result := Self;
end;

function TQuery<M>.Limit(N: Integer): TQuery<M>;
begin
  FLimit := N;
  Result := Self;
end;

function TQuery<M>.Offset(N: Integer): TQuery<M>;
begin
  FOffset := N;
  Result := Self;
end;

function TQuery<M>.Preload(const Relations: array of string): TQuery<M>;
var
  I, N: Integer;
begin
  N := Length(FPreloads);
  SetLength(FPreloads, N + Length(Relations));
  for I := 0 to High(Relations) do
  begin
    if FMeta.IndexOfRelation(Relations[I]) < 0 then
      raise EQueryError.CreateFmt('%s has no relation "%s"',
        [FMeta.ModelClass.ClassName, Relations[I]]);
    FPreloads[N + I] := Relations[I];
  end;
  Result := Self;
end;

function TQuery<M>.WithTrashed: TQuery<M>;
begin
  FTrashed := tsWith;
  Result := Self;
end;

function TQuery<M>.OnlyTrashed: TQuery<M>;
begin
  FTrashed := tsOnly;
  Result := Self;
end;

{ True when the query needs an extra clause about deleted_at. }
function TQuery<M>.SoftDeleteClause(out Only: Boolean): Boolean;
begin
  Only := FTrashed = tsOnly;
  Result := FMeta.SoftDeletes and (FTrashed <> tsWith);
end;

procedure TQuery<M>.BuildWhere(var B: TStrBuilder; var ParamNo: Integer;
  var Params: TArray<TDbParam>);
var
  I, J: Integer;
  W: PWhereTerm;
  C: TDbConnection;
  Filter, TrashedOnly, IsFirst: Boolean;

  { Closes an OR group when the clause we just wrote was its last. }
  procedure CloseGroup(Idx: Integer);
  var
    InGroup, LastInGroup: Boolean;
  begin
    InGroup := (FWheres + Idx)^.OrPrev or
      ((Idx + 1 < FWhereCount) and (FWheres + Idx + 1)^.OrPrev);
    LastInGroup := (Idx + 1 >= FWhereCount) or
      not (FWheres + Idx + 1)^.OrPrev;
    if InGroup and LastInGroup then
      B.AppendByte(Ord(')'));
  end;

begin
  Filter := SoftDeleteClause(TrashedOnly);
  if (FWhereCount = 0) and not Filter then
    Exit;
  C := Conn;
  B.Append(' WHERE ');
  IsFirst := True;

  if Filter then
  begin
    { Qualified with the table name, so the clause also holds when the
      query gains a join. }
    C.AppendIdentStr(B, FMeta.Table);
    B.AppendByte(Ord('.'));
    C.AppendIdentStr(B, FMeta.DeletedAtColumn);
    if TrashedOnly then
      B.Append(' IS NOT NULL')
    else
      B.Append(' IS NULL');
    IsFirst := False;
  end;

  for I := 0 to FWhereCount - 1 do
  begin
    W := FWheres + I;
    if W^.OrPrev then
      B.Append(' OR ')
    else
    begin
      if not IsFirst then
        B.Append(' AND ');
      IsFirst := False;
      { The start of an OR group: the parenthesis has to go around the whole
        group, or AND binds to the first clause alone. }
      if (I + 1 < FWhereCount) and (FWheres + I + 1)^.OrPrev then
        B.AppendByte(Ord('('));
    end;
    if W^.Table <> '' then
    begin
      C.AppendIdentStr(B, string(W^.Table));
      B.AppendByte(Ord('.'));
    end;
    C.AppendIdentStr(B, string(W^.Column));

    if W^.NullCheck then
    begin
      if W^.WantNull then
        B.Append(' IS NULL')
      else
        B.Append(' IS NOT NULL');
      CloseGroup(I);
      Continue;
    end;

    if W^.InList then
    begin
      if W^.ParamCount = 0 then
      begin
        { IN () er ugyldig SQL. En tom liste matcher ingenting. }
        B.Append(' IN (NULL)');
        Continue;
      end;
      B.Append(' IN (');
      for J := 0 to W^.ParamCount - 1 do
      begin
        if J > 0 then
          B.Append(', ');
        Inc(ParamNo);
        C.AppendPlaceholder(B, ParamNo);
        SetLength(Params, ParamNo);
        Params[ParamNo - 1] := FInParams[W^.ParamFirst + J];
      end;
      B.AppendByte(Ord(')'));
      CloseGroup(I);
      Continue;
    end;

    B.Append(OpText(W^.Op, C.Dialect));
    Inc(ParamNo);
    C.AppendPlaceholder(B, ParamNo);
    SetLength(Params, ParamNo);
    Params[ParamNo - 1] := W^.Param;
    CloseGroup(I);
  end;
end;

procedure TQuery<M>.BuildTail(var B: TStrBuilder);
var
  I: Integer;
  O: POrderTerm;
  C: TDbConnection;
begin
  C := Conn;
  if FOrderCount > 0 then
  begin
    B.Append(' ORDER BY ');
    for I := 0 to FOrderCount - 1 do
    begin
      O := FOrders + I;
      if I > 0 then
        B.Append(', ');
      if O^.Table <> '' then
      begin
        C.AppendIdentStr(B, string(O^.Table));
        B.AppendByte(Ord('.'));
      end;
      C.AppendIdentStr(B, string(O^.Column));
      if O^.Dir = Desc then
        B.Append(' DESC');
    end;
  end;
  if FLimit >= 0 then
  begin
    B.Append(' LIMIT ');
    B.AppendInt(FLimit);
  end;
  if FOffset > 0 then
  begin
    B.Append(' OFFSET ');
    B.AppendInt(FOffset);
  end;
end;

function TQuery<M>.ToSql: string;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo, I: Integer;
  C: TDbConnection;
  Mark: TArenaMark;
begin
  C := Conn;
  Mark := Arena.Mark;
  try
    B.Init(Arena, 256);
    B.Append('SELECT ');
    for I := 0 to FMeta.ColumnCount - 1 do
    begin
      if I > 0 then
        B.Append(', ');
      C.AppendIdentStr(B, FMeta.Table);
      B.AppendByte(Ord('.'));
      C.AppendIdentStr(B, FMeta.Columns[I].ColumnName);
    end;
    B.Append(' FROM ');
    C.AppendIdentStr(B, FMeta.Table);
    ParamNo := 0;
    BuildWhere(B, ParamNo, Params);
    BuildTail(B);
    Result := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;
end;

function TQuery<M>.Get: TModelList<M>;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo, I, J: Integer;
  C: TDbConnection;
  R: TDbResult;
  Item: M;
  Sql: string;
  Mark: TArenaMark;
begin
  C := Conn;
  Mark := Arena.Mark;
  try
    B.Init(Arena, 256);
    B.Append('SELECT ');
    for I := 0 to FMeta.ColumnCount - 1 do
    begin
      if I > 0 then
        B.Append(', ');
      C.AppendIdentStr(B, FMeta.Table);
      B.AppendByte(Ord('.'));
      C.AppendIdentStr(B, FMeta.Columns[I].ColumnName);
    end;
    B.Append(' FROM ');
    C.AppendIdentStr(B, FMeta.Table);
    ParamNo := 0;
    BuildWhere(B, ParamNo, Params);
    BuildTail(B);
    Sql := B.ToString;
  finally
    { The SQL text has been copied out; the build buffer is not needed. The
      parameters live in their own allocations, which are older than the
      mark and survive. }
    Arena.Rewind(Mark);
  end;

  R := C.ExecParams(Arena, Sql, Params);
  Result := TModelList<M>.Create;
  for I := 0 to R.RowCount - 1 do
  begin
    Item := M.Create;
    Item.Hydrate(R, I);
    Result.Add(Item);
  end;

  for J := 0 to High(FPreloads) do
    LoadRelation(Result, FPreloads[J]);
end;

{ A BelongsToMany in one query for the whole list: the target's rows
  joined to the pivot, with the pivot's key back to the owner selected
  under a name no model column can have. Each column is selected as
  itself -- "tags"."name" AS "name" -- so Hydrate finds it by the same
  name whichever driver reports it.

  A soft-deleted target is left out, as a query for it would. It is
  still attached, and RelatedIds still says so. }
procedure LoadManyToMany(List: TModelListBase; Meta: TModelMeta;
  const Rel: TRelationInfo; C: TDbConnection; A: TArena);
const
  OwnerAlias = 'askr_pivot_owner';
var
  Target: TModelMeta;
  Keys: TArray<Int64>;
  Params: TArray<TDbParam>;
  B: TStrBuilder;
  Sql: string;
  Mark: TArenaMark;
  R: TDbResult;
  I, J, Col: Integer;
  Slot: PPointer;
  Child: TModel;
  OwnerKey: Int64;
begin
  Target := Rel.Target.Meta;
  SetLength(Keys, List.Count);
  SetLength(Params, List.Count);
  for I := 0 to List.Count - 1 do
  begin
    Keys[I] := List.Item(I).PrimaryKeyValue;
    Params[I] := DbParam(A, Keys[I]);
  end;

  Mark := A.Mark;
  try
    B.Init(A, 384);
    B.Append('SELECT ');
    for I := 0 to Target.ColumnCount - 1 do
    begin
      C.AppendIdentStr(B, Target.Table);
      B.AppendByte(Ord('.'));
      C.AppendIdentStr(B, Target.Columns[I].ColumnName);
      B.Append(' AS ');
      C.AppendIdentStr(B, Target.Columns[I].ColumnName);
      B.Append(', ');
    end;
    C.AppendIdentStr(B, Rel.Pivot);
    B.AppendByte(Ord('.'));
    C.AppendIdentStr(B, Rel.ForeignKey);
    B.Append(' AS ');
    C.AppendIdentStr(B, OwnerAlias);
    B.Append(' FROM ');
    C.AppendIdentStr(B, Target.Table);
    B.Append(' JOIN ');
    C.AppendIdentStr(B, Rel.Pivot);
    B.Append(' ON ');
    C.AppendIdentStr(B, Rel.Pivot);
    B.AppendByte(Ord('.'));
    C.AppendIdentStr(B, Rel.PivotRelatedKey);
    B.Append(' = ');
    C.AppendIdentStr(B, Target.Table);
    B.AppendByte(Ord('.'));
    C.AppendIdentStr(B, Target.PrimaryKey);
    B.Append(' WHERE ');
    C.AppendIdentStr(B, Rel.Pivot);
    B.AppendByte(Ord('.'));
    C.AppendIdentStr(B, Rel.ForeignKey);
    B.Append(' IN (');
    for I := 0 to High(Keys) do
    begin
      if I > 0 then
        B.Append(', ');
      C.AppendPlaceholder(B, I + 1);
    end;
    B.AppendByte(Ord(')'));
    if Target.SoftDeletes then
    begin
      B.Append(' AND ');
      C.AppendIdentStr(B, Target.Table);
      B.AppendByte(Ord('.'));
      C.AppendIdentStr(B, Target.DeletedAtColumn);
      B.Append(' IS NULL');
    end;
    { The target's key, so the order is the same on every database and
      on every load. }
    B.Append(' ORDER BY ');
    C.AppendIdentStr(B, Target.Table);
    B.AppendByte(Ord('.'));
    C.AppendIdentStr(B, Target.PrimaryKey);
    Sql := B.ToString;
  finally
    A.Rewind(Mark);
  end;

  R := C.ExecParams(A, Sql, Params);

  { An empty list for every owner first, so one with no rows says "none"
    rather than "not loaded". }
  for I := 0 to List.Count - 1 do
  begin
    Slot := PPointer(List.Item(I).FieldAddress(Rel.Name));
    if Slot = nil then
      raise EQueryError.CreateFmt(
        '%s is missing a published field "%s" to hold the relation',
        [Meta.ModelClass.ClassName, Rel.Name]);
    Slot^ := Pointer(TModelListBase.Create);
  end;

  Col := R.IndexOfField(OwnerAlias);
  for J := 0 to R.RowCount - 1 do
  begin
    OwnerKey := R.Value(J, Col).ToIntDef(0);
    { A new child per owner: the same tag on two posts is two objects,
      so a change to one through its owner does not show on the other. }
    for I := 0 to List.Count - 1 do
    begin
      if Keys[I] <> OwnerKey then
        Continue;
      Child := TModel(Rel.Target.NewInstance);
      Child.Create;
      Child.Hydrate(R, J);
      Slot := PPointer(List.Item(I).FieldAddress(Rel.Name));
      TModelListBase(Slot^).AddModel(Child);
    end;
  end;
end;

procedure TQuery<M>.LoadRelation(List: TModelList<M>; const RelName: string);
var
  Rel: TRelationInfo;
  RelIdx, I, J, Col: Integer;
  Keys: TArray<Int64>;
  Params: TArray<TDbParam>;
  B: TStrBuilder;
  C: TDbConnection;
  R: TDbResult;
  ChildMeta: TModelMeta;
  Sql: string;
  Mark: TArenaMark;
  Slot: PPointer;
  Child: TModel;
  Owner: TModel;
  ParentKey: Int64;
  FkIdx: Integer;
begin
  if List.Count = 0 then
    Exit;
  RelIdx := FMeta.IndexOfRelation(RelName);
  if RelIdx < 0 then
    Exit;
  Rel := FMeta.Relations[RelIdx];
  C := Conn;
  if Rel.Kind = rkBelongsToMany then
  begin
    LoadManyToMany(List, FMeta, Rel, C, Arena);
    Exit;
  end;
  ChildMeta := Rel.Target.Meta;

  { The keys to look up on. For HasMany and HasOne it is the parent's
    primary key; for BelongsTo it is the foreign key in the parent row. }
  SetLength(Keys, List.Count);
  if Rel.Kind = rkBelongsTo then
  begin
    FkIdx := FMeta.IndexOfColumn(Rel.ForeignKey);
    if FkIdx < 0 then
      raise EQueryError.CreateFmt('%s is missing column "%s" for relation "%s"',
        [FMeta.ModelClass.ClassName, Rel.ForeignKey, RelName]);
    for I := 0 to List.Count - 1 do
      Keys[I] := GetInt64Prop(List[I], FMeta.Columns[FkIdx].Prop);
  end
  else
    for I := 0 to List.Count - 1 do
      Keys[I] := List[I].PrimaryKeyValue;

  { The parameters have to be allocated BEFORE the mark. If they sit after
    it, Rewind moves the bump pointer back past them, and the next
    allocations — ExecParams's own null-terminated copies — overwrite the
    values while they are being read. }
  SetLength(Params, Length(Keys));
  for I := 0 to High(Keys) do
    Params[I] := DbParam(Arena, Keys[I]);

  Mark := Arena.Mark;
  try
    B.Init(Arena, 256);
    B.Append('SELECT ');
    for I := 0 to ChildMeta.ColumnCount - 1 do
    begin
      if I > 0 then
        B.Append(', ');
      C.AppendIdentStr(B, ChildMeta.Columns[I].ColumnName);
    end;
    B.Append(' FROM ');
    C.AppendIdentStr(B, ChildMeta.Table);
    B.Append(' WHERE ');
    if Rel.Kind = rkBelongsTo then
      C.AppendIdentStr(B, Rel.LocalKey)
    else
      C.AppendIdentStr(B, Rel.ForeignKey);
    B.Append(' IN (');
    for I := 0 to High(Keys) do
    begin
      if I > 0 then
        B.Append(', ');
      C.AppendPlaceholder(B, I + 1);
    end;
    B.AppendByte(Ord(')'));
    Sql := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;

  { One query for the whole set. That is what keeps a loop over the
    relation from becoming N+1. }
  R := C.ExecParams(Arena, Sql, Params);

  { The children go into a published field on the parent model, found with
    FieldAddress. The field has to have the same name as the relation. }
  for I := 0 to List.Count - 1 do
  begin
    Slot := PPointer(List[I].FieldAddress(RelName));
    if Slot = nil then
      raise EQueryError.CreateFmt(
        '%s is missing a published field "%s" to hold the relation',
        [FMeta.ModelClass.ClassName, RelName]);
    if Rel.Kind = rkHasMany then
      Slot^ := Pointer(TModelListBase.Create)
    else
      Slot^ := nil;
  end;

  if Rel.Kind = rkBelongsTo then
    Col := R.IndexOfField(Rel.LocalKey)
  else
    Col := R.IndexOfField(Rel.ForeignKey);

  for J := 0 to R.RowCount - 1 do
  begin
    Child := TModel(Rel.Target.NewInstance);
    Child.Create;
    Child.Hydrate(R, J);
    if Col < 0 then
      Continue;
    ParentKey := R.Value(J, Col).ToIntDef(0);
    for I := 0 to List.Count - 1 do
    begin
      Owner := List[I];
      if Keys[I] <> ParentKey then
        Continue;
      Slot := PPointer(Owner.FieldAddress(RelName));
      if Rel.Kind = rkHasMany then
        TModelListBase(Slot^).AddModel(Child)
      else
        Slot^ := Pointer(Child);
      if Rel.Kind <> rkHasMany then
        Break;
    end;
  end;
end;

function TQuery<M>.First: M;
var
  L: TModelList<M>;
begin
  FLimit := 1;
  L := Get;
  Result := L.First;
end;

function TQuery<M>.Find(Id: Int64): M;
var
  Col: TColInt64;
begin
  Col := ColInt64(FMeta.Table, FMeta.PrimaryKey);
  Result := Where(Col, Eq, Id).First;
end;

function TQuery<M>.Count: Int64;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo: Integer;
  C: TDbConnection;
  R: TDbResult;
  Sql: string;
  Mark: TArenaMark;
begin
  C := Conn;
  Mark := Arena.Mark;
  try
    B.Init(Arena, 128);
    B.Append('SELECT count(*) FROM ');
    C.AppendIdentStr(B, FMeta.Table);
    ParamNo := 0;
    BuildWhere(B, ParamNo, Params);
    Sql := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;
  R := C.ExecParams(Arena, Sql, Params);
  if R.IsEmpty then
    Exit(0);
  Result := R.AsInt64(0, 0);
end;

function TQuery<M>.Paginate(Page, PerPage: Integer): TModelList<M>;
var
  O: POrderTerm;
  Pk: string;
  I: Integer;
  Have: Boolean;
begin
  if Page < 1 then
    Page := 1;
  if PerPage < 1 then
    PerPage := 25;

  { The primary key goes on the end of the ORDER BY, always.

    LIMIT and OFFSET cut a page out of an order, and where the order does
    not decide between two rows, the database is free to put them either
    way round -- on each query. Page 1 then shows a row that page 2 shows
    again, and some other row is never shown at all. It is not a rare
    case: it is every sort over a column with repeats, which is most of
    them, and nothing says a word when it happens.

    The key is unique by definition, so adding it last makes the order
    total without changing what the caller asked for. Ascending
    regardless of the sort direction: the point is that it is decided,
    not which way. }
  Pk := FMeta.PrimaryKey;
  if Pk <> '' then
  begin
    Have := False;
    for I := 0 to FOrderCount - 1 do
      if (FOrders + I)^.Column = Pk then
      begin
        Have := True;
        Break;
      end;
    if not Have then
    begin
      O := AddOrder;
      O^.Table := FMeta.Table;
      O^.Column := Pk;
      O^.Dir := Asc;
    end;
  end;

  FLimit := PerPage;
  FOffset := (Page - 1) * PerPage;
  Result := Get;
end;

function TQuery<M>.DeleteAll: Int64;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo: Integer;
  C: TDbConnection;
  R: TDbResult;
  Sql: string;
  Mark: TArenaMark;
begin
  { With SoftDeletes, DeleteAll does the same as Model.Delete. The
    alternative — one deleting softly and the other hard — is the kind of
    difference nobody remembers until a table is empty. }
  if FMeta.SoftDeletes then
    Exit(SoftDeleteAll);

  C := Conn;
  Mark := Arena.Mark;
  try
    B.Init(Arena, 128);
    B.Append('DELETE FROM ');
    C.AppendIdentStr(B, FMeta.Table);
    ParamNo := 0;
    BuildWhere(B, ParamNo, Params);
    Sql := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;
  R := C.ExecParams(Arena, Sql, Params);
  Result := R.AffectedRows;
end;

function TQuery<M>.SoftDeleteAll: Int64;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo: Integer;
  C: TDbConnection;
  R: TDbResult;
  Sql: string;
  Mark: TArenaMark;
begin
  C := Conn;
  Mark := Arena.Mark;
  try
    { The timestamp is parameter number one, and the other clauses count on
      from there. Get that wrong and every filter points one place off. }
    SetLength(Params, 1);
    Params[0] := DbParamDateTime(Arena, UtcNow);
    ParamNo := 1;

    B.Init(Arena, 160);
    B.Append('UPDATE ');
    C.AppendIdentStr(B, FMeta.Table);
    B.Append(' SET ');
    C.AppendIdentStr(B, FMeta.DeletedAtColumn);
    B.Append(' = ');
    C.AppendPlaceholder(B, 1);
    BuildWhere(B, ParamNo, Params);
    Sql := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;
  R := C.ExecParams(Arena, Sql, Params);
  Result := R.AffectedRows;
end;

function TQuery<M>.ForceDeleteAll: Int64;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo: Integer;
  C: TDbConnection;
  R: TDbResult;
  Sql: string;
  Mark: TArenaMark;
begin
  C := Conn;
  Mark := Arena.Mark;
  try
    B.Init(Arena, 128);
    B.Append('DELETE FROM ');
    C.AppendIdentStr(B, FMeta.Table);
    ParamNo := 0;
    BuildWhere(B, ParamNo, Params);
    Sql := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;
  R := C.ExecParams(Arena, Sql, Params);
  Result := R.AffectedRows;
end;

function TQuery<M>.RestoreAll: Int64;
var
  B: TStrBuilder;
  Params: TArray<TDbParam>;
  ParamNo: Integer;
  C: TDbConnection;
  R: TDbResult;
  Sql: string;
  Mark: TArenaMark;
begin
  if not FMeta.SoftDeletes then
    raise EDbError.CreateFmt('%s has no soft deletes; nothing to restore.',
      [FMeta.ModelClass.ClassName]);
  { Only the deleted ones are candidates, unless the caller has said
    otherwise. }
  if FTrashed = tsWithout then
    FTrashed := tsOnly;
  C := Conn;
  Mark := Arena.Mark;
  try
    SetLength(Params, 0);
    ParamNo := 0;
    B.Init(Arena, 160);
    B.Append('UPDATE ');
    C.AppendIdentStr(B, FMeta.Table);
    B.Append(' SET ');
    C.AppendIdentStr(B, FMeta.DeletedAtColumn);
    B.Append(' = NULL');
    BuildWhere(B, ParamNo, Params);
    Sql := B.ToString;
  finally
    Arena.Rewind(Mark);
  end;
  R := C.ExecParams(Arena, Sql, Params);
  Result := R.AffectedRows;
end;

class function TQuery<M>.New: TQuery<M>;
begin
  Result := TQuery<M>.Create(M, nil);
end;

class function TQuery<M>.Using(AConn: TDbConnection): TQuery<M>;
begin
  Result := TQuery<M>.Create(M, AConn);
end;

end.
