{ GENERATED BY askr build (Rún) — DO NOT EDIT.

  Emitted from shop.run, with the schema
  read from sqlite:.build/run/shop.db at that same moment. This file is an
  intermediate: it belongs in the build directory, not in source. }
unit Shop.Gen;

{$mode Delphi}{$H+}

interface

uses
  SysUtils, Askr.Core.Arena, Askr.Core.Text, Askr.Urd.Driver;

type
  { orders — fields and types read from the schema at comptime }
  TOrderRow = record
    Id: Int64;   { INTEGER }
    CustomerId: Int64;   { INTEGER }
    Amount: Currency;   { NUMERIC(12,2) }
    Shipped: Boolean;   { TINYINT(1) }
  end;
  TOrderRowArray = array of TOrderRow;

  { customers — fields and types read from the schema at comptime }
  TCustomerRow = record
    Id: Int64;   { INTEGER }
    Name: string;   { TEXT }
    Email: string;   { TEXT }
    Balance: Currency;   { NUMERIC(12,2) }
    Active: Boolean;   { TINYINT(1) }
    Weight: Double;   { REAL }
    CreatedAt: string;   { TEXT }
    Orders: TOrderRowArray;   { orders.customer_id }
  end;
  TCustomerRowArray = array of TCustomerRow;

function CustomerById(A: TArena; C: TDbConnection; Id: Int64; out Found: Boolean): TCustomerRow;
function OrderById(A: TArena; C: TDbConnection; Id: Int64; out Found: Boolean): TOrderRow;
function ActiveCustomers(A: TArena; C: TDbConnection; MinBalance: Currency): TCustomerRowArray;
function CustomersMissingWeight(A: TArena; C: TDbConnection): TCustomerRowArray;
function LargeOrders(A: TArena; C: TDbConnection; Floor: Currency): TOrderRowArray;
function SearchCustomers(A: TArena; C: TDbConnection; Pattern: string): TCustomerRowArray;

implementation

function ReadOrderRow(R: TDbResult; Row: Integer): TOrderRow;
var
  Row_: TOrderRow;
begin
  SqlToInt64(R.Value(Row, 0), Row_.Id);
  SqlToInt64(R.Value(Row, 1), Row_.CustomerId);
  SqlToCurrency(R.Value(Row, 2), Row_.Amount);
  SqlToBool(R.Value(Row, 3), Row_.Shipped);
  Result := Row_;
end;

function ReadCustomerRow(R: TDbResult; Row: Integer): TCustomerRow;
var
  Row_: TCustomerRow;
begin
  SqlToInt64(R.Value(Row, 0), Row_.Id);
  Row_.Name := R.Value(Row, 1).ToString;
  Row_.Email := R.Value(Row, 2).ToString;
  SqlToCurrency(R.Value(Row, 3), Row_.Balance);
  SqlToBool(R.Value(Row, 4), Row_.Active);
  SqlToFloat(R.Value(Row, 5), Row_.Weight);
  Row_.CreatedAt := R.Value(Row, 6).ToString;
  Result := Row_;
end;

function CustomerById(A: TArena; C: TDbConnection; Id: Int64; out Found: Boolean): TCustomerRow;
var
  R: TDbResult;
  I: Integer;
begin
  Result := Default(TCustomerRow);
  R := C.ExecParams(A,
    'SELECT "id", "name", "email", "balance", "active", "weight", "created_at" FROM "customers" WHERE "id" = ? LIMIT 1',
    [DbParam(A, Id)]);
  Found := R.RowCount > 0;
  if Found then
    Result := ReadCustomerRow(R, 0);
end;

function OrderById(A: TArena; C: TDbConnection; Id: Int64; out Found: Boolean): TOrderRow;
var
  R: TDbResult;
  I: Integer;
begin
  Result := Default(TOrderRow);
  R := C.ExecParams(A,
    'SELECT "id", "customer_id", "amount", "shipped" FROM "orders" WHERE "id" = ? LIMIT 1',
    [DbParam(A, Id)]);
  Found := R.RowCount > 0;
  if Found then
    Result := ReadOrderRow(R, 0);
end;

function ActiveCustomers(A: TArena; C: TDbConnection; MinBalance: Currency): TCustomerRowArray;
var
  R: TDbResult;
  I: Integer;
  Rows: TCustomerRowArray;
  Ids: TStrBuilder;
  RR: TDbResult;
  J: Integer;
begin
  R := C.ExecParams(A,
    'SELECT "id", "name", "email", "balance", "active", "weight", "created_at" FROM "customers" WHERE "balance" >= ? AND "active" = ? ORDER BY "balance" DESC, "name" LIMIT 10',
    [DbParam(A, MinBalance), DbParam(A, true)]);
  SetLength(Rows, R.RowCount);
  for I := 0 to R.RowCount - 1 do
    Rows[I] := ReadCustomerRow(R, I);

  { orders: orders.customer_id -> customers.id, read from the schema }
  if Length(Rows) > 0 then
  begin
    Ids.Init(A, 128);
    for I := 0 to High(Rows) do
    begin
      if I > 0 then Ids.Append(',');
      Ids.Append(IntToStr(Rows[I].Id));
    end;
    RR := C.Exec(A,
      'SELECT "id", "customer_id", "amount", "shipped" FROM "orders" WHERE "customer_id" IN (' + Ids.ToString + ')');
    for I := 0 to High(Rows) do
      for J := 0 to RR.RowCount - 1 do
        if Rows[I].Id = StrToInt64Def(RR.Value(J, 1).ToString, -1) then
        begin
          SetLength(Rows[I].Orders,
            Length(Rows[I].Orders) + 1);
          Rows[I].Orders[High(Rows[I].Orders)] :=
            ReadOrderRow(RR, J);
        end;
  end;
  Result := Rows;
end;

function CustomersMissingWeight(A: TArena; C: TDbConnection): TCustomerRowArray;
var
  R: TDbResult;
  I: Integer;
  Rows: TCustomerRowArray;
begin
  R := C.ExecParams(A,
    'SELECT "id", "name", "email", "balance", "active", "weight", "created_at" FROM "customers" WHERE "weight" IS NULL',
    []);
  SetLength(Rows, R.RowCount);
  for I := 0 to R.RowCount - 1 do
    Rows[I] := ReadCustomerRow(R, I);
  Result := Rows;
end;

function LargeOrders(A: TArena; C: TDbConnection; Floor: Currency): TOrderRowArray;
var
  R: TDbResult;
  I: Integer;
  Rows: TOrderRowArray;
begin
  R := C.ExecParams(A,
    'SELECT "id", "customer_id", "amount", "shipped" FROM "orders" WHERE "amount" >= ? ORDER BY "amount" DESC LIMIT 5',
    [DbParam(A, Floor)]);
  SetLength(Rows, R.RowCount);
  for I := 0 to R.RowCount - 1 do
    Rows[I] := ReadOrderRow(R, I);
  Result := Rows;
end;

function SearchCustomers(A: TArena; C: TDbConnection; Pattern: string): TCustomerRowArray;
var
  R: TDbResult;
  I: Integer;
  Rows: TCustomerRowArray;
begin
  R := C.ExecParams(A,
    'SELECT "id", "name", "email", "balance", "active", "weight", "created_at" FROM "customers" WHERE "email" LIKE ? ORDER BY "name"',
    [DbParam(A, Pattern)]);
  SetLength(Rows, R.RowCount);
  for I := 0 to R.RowCount - 1 do
    Rows[I] := ReadCustomerRow(R, I);
  Result := Rows;
end;

end.
