#!/usr/bin/env python3
# Writes tests/vectors/aead.txt: ChaCha20-Poly1305 and Poly1305 vectors made
# with python-cryptography, which computes them through OpenSSL -- an
# implementation of RFC 8439 that is not ours. Lengths sit on either side
# of every block edge, where padding and carries go wrong; RFC 8439's own
# Appendix A.3 Poly1305 cases, the ones built to hit the hard carries, are
# at the end.
#
#   python3 tools/vectors/aead.py > tests/vectors/aead.txt
import os
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.hazmat.primitives import poly1305

print('# ChaCha20-Poly1305 and Poly1305 vectors. Generated by tools/vectors/aead.py')
print('# with python-cryptography (OpenSSL). Do not edit.')
print('# aead|key|nonce|aad|plain|sealed   poly|key|msg|tag   -- hex')
for plen in [0, 1, 15, 16, 17, 31, 32, 33, 63, 64, 65, 127, 128, 129, 255, 256, 257, 1000]:
    for alen in [0, 1, 12, 16, 17, 33]:
        k, n = os.urandom(32), os.urandom(12)
        a, p = os.urandom(alen), os.urandom(plen)
        s = ChaCha20Poly1305(k).encrypt(n, p, a)
        print('aead|%s|%s|%s|%s|%s' % (k.hex(), n.hex(), a.hex(), p.hex(), s.hex()))
for mlen in [0, 1, 15, 16, 17, 31, 32, 33, 63, 64, 65, 200]:
    for _ in range(3):
        k, m = os.urandom(32), os.urandom(mlen)
        print('poly|%s|%s|%s' % (k.hex(), m.hex(), poly1305.Poly1305.generate_tag(k, m).hex()))
# RFC 8439 A.3 #5-#11: r and s chosen to make every carry path run.
def h(s): return bytes.fromhex(s.replace(' ', ''))
cases = [
    ('02' + '00' * 31, 'ff' * 16),
    ('02' + '00' * 15 + 'ff' * 16, '02' + '00' * 15),
    ('01' + '00' * 31, 'ff' * 16 + 'f0' + 'ff' * 15 + '11' + '00' * 15),
    ('01' + '00' * 31, 'ff' * 16 + 'fb' + 'fe' * 15 + '01' * 16),
    ('02' + '00' * 31, 'fd' + 'ff' * 15),
    ('01' + '00' * 7 + '04' + '00' * 7 + '00' * 16,
     'e33594d7505e43b900000000000000003394d7505e4379cd010000000000000000000000000000000000000000000000'
     '01000000000000000000000000000000'),
    ('01' + '00' * 7 + '04' + '00' * 7 + '00' * 16,
     'e33594d7505e43b900000000000000003394d7505e4379cd01' + '00' * 7 + '00' * 16),
]
for key, msg in cases:
    k, m = h(key), h(msg)
    print('poly|%s|%s|%s' % (k.hex(), m.hex(), poly1305.Poly1305.generate_tag(k, m).hex()))
