#!/usr/bin/env python3
# Writes tests/vectors/qr.txt: QR codes made by python-qrcode (pip install
# qrcode), an encoder that is not ours, in byte mode at a fixed mask, so
# every module is determined by the standard and Askr.Qr has to match each
# one. Every error correction level, every mask, and versions from 1 to 40.
#
#   python3 tools/vectors/qr.py > tests/vectors/qr.txt
import random
import qrcode
from qrcode.util import QRData, MODE_8BIT_BYTE

LEVELS = [('L', qrcode.constants.ERROR_CORRECT_L), ('M', qrcode.constants.ERROR_CORRECT_M),
          ('Q', qrcode.constants.ERROR_CORRECT_Q), ('H', qrcode.constants.ERROR_CORRECT_H)]
rnd = random.Random(20260926)
samples = [
    b'', b'a', b'Hello, world!', 'blåbærsyltetøy 🫐'.encode(),
    b'otpauth://totp/My%20Shop:ada@example.com?secret=JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP&issuer=My%20Shop&algorithm=SHA1&digits=6&period=30',
]
for n in [14, 15, 26, 42, 62, 84, 106, 122, 152, 180, 213, 251, 287, 331, 362, 412, 450, 504, 560, 624, 666, 711,
          779, 857, 911, 997, 1059, 1125, 1190, 1264, 1370, 1452, 1538, 1628, 1722, 1809, 1911, 1989, 2099, 2213, 2331, 2953]:
    samples.append(bytes(rnd.randrange(256) for _ in range(n)))

def hexrow(row):
    bits = ''.join('1' if c else '0' for c in row)
    bits += '0' * (-len(bits) % 4)
    return '%x' % int(bits, 2) if bits else ''

print('# QR codes by python-qrcode, byte mode, fixed mask. Generated by tools/vectors/qr.py. Do not edit.')
print('# level|mask|version|data hex|each row as hex, padded to whole digits, joined with /')
i = 0
for k, data in enumerate(samples):
    # Every level for the short ones; one each, in turn, for the long ones,
    # so the file stays small and every level still reaches version 40.
    levels = LEVELS if k < 5 else [LEVELS[k % 4]]
    for name, level in levels:
        mask = i % 8
        i += 1
        q = qrcode.QRCode(error_correction=level, mask_pattern=mask, border=0, box_size=1)
        q.add_data(QRData(data, mode=MODE_8BIT_BYTE))
        try:
            q.make(fit=True)
        except Exception:
            continue          # too long for this level
        m = q.get_matrix()
        width = len(m) + (-len(m) % 4)
        print('%s|%d|%d|%s|%s' % (name, mask, q.version, data.hex(),
                                  '/'.join(hexrow(row).rjust(width // 4, '0') for row in m)))

# The mask the penalty score picks, held to Nayuki's qrcodegen (pip install
# qrcodegen), which scores the 2015 text -- 1:1:3:1:1 at any width, the
# quiet zone light -- on the finished symbol. python-qrcode scores with the
# format bits left light, so its choice is not one to match.
import qrcodegen
from qrcodegen import QrCode, QrSegment
GEN = {'L': QrCode.Ecc.LOW, 'M': QrCode.Ecc.MEDIUM, 'Q': QrCode.Ecc.QUARTILE, 'H': QrCode.Ecc.HIGH}
rnd = random.Random(7)
for k in range(64):
    n = rnd.choice([3, 10, 20, 40, 80, 120, 200, 400, 700])
    data = bytes(rnd.randrange(32, 127) for _ in range(n))
    name = 'LMQH'[k % 4]
    q = QrCode.encode_segments([QrSegment.make_bytes(data)], GEN[name], boostecl=False)
    size = q.get_size()
    width = size + (-size % 4)
    rows = [[q.get_module(x, y) for x in range(size)] for y in range(size)]
    print('%s|-1|%d|%s|%s' % (name, q.get_version(), data.hex(),
                              '/'.join(hexrow(r).rjust(width // 4, '0') for r in rows)))
