#!/usr/bin/env python3
# Writes tests/vectors/sigv4.txt: AWS Signature V4 for S3, made by botocore
# (pip install botocore) -- AWS's own signer -- at a fixed time, for the
# requests Askr.Storage makes: PUT, GET, HEAD and DELETE with a signed
# payload hash, and presigned GET URLs. Keys with spaces, plus signs and
# letters outside ASCII, path-style and virtual-host style.
#
#   python3 tools/vectors/sigv4.py > tests/vectors/sigv4.txt
import datetime, hashlib
from unittest import mock
from urllib.parse import quote
from botocore.auth import S3SigV4Auth, S3SigV4QueryAuth
from botocore.awsrequest import AWSRequest
from botocore.credentials import Credentials

creds = Credentials('AKIDEXAMPLE', 'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY')
when = datetime.datetime(2026, 9, 26, 12, 30, 45, tzinfo=datetime.timezone.utc)
amzdate = when.strftime('%Y%m%dT%H%M%SZ')

def key_path(key):
    # What Askr.Storage puts in the URL: every byte but unreserved ones
    # and / percent-encoded.
    return quote(key.encode('utf-8'), safe='/~')

cases = [
    ('http://127.0.0.1:9000/assets', 'us-east-1', 'avatars/42.png'),
    ('https://s3.eu-north-1.amazonaws.com/my-bucket', 'eu-north-1', 'photos/2026/ferie på Ås.jpg'),
    ('https://my-bucket.s3.eu-west-1.amazonaws.com', 'eu-west-1', 'a+b=c&d e.txt'),
]
print('# AWS Signature V4 for S3 by botocore, at ' + amzdate + '. Generated by tools/vectors/sigv4.py. Do not edit.')
print('# method|url|region|body hex|x-amz-content-sha256|authorization     presign|url|region|expires|url')
with mock.patch('botocore.auth.get_current_datetime', return_value=when):
    for base, region, key in cases:
        url = base + '/' + key_path(key)
        for method, body in [('PUT', b'hello \x00\xff world'), ('GET', b''), ('HEAD', b''), ('DELETE', b'')]:
            sha = hashlib.sha256(body).hexdigest()
            r = AWSRequest(method=method, url=url, data=body,
                           headers={'x-amz-content-sha256': sha})
            S3SigV4Auth(creds, 's3', region).add_auth(r)
            print('%s|%s|%s|%s|%s|%s' % (method, url, region, body.hex(), sha, r.headers['Authorization']))
        for expires in [60, 604800]:
            r = AWSRequest(method='GET', url=url)
            S3SigV4QueryAuth(creds, 's3', region, expires=expires).add_auth(r)
            print('presign|%s|%s|%d|%s' % (url, region, expires, r.url))
