{ Askr.Core.LangData -- numbers and dates, per locale, from ICU.

  Generated by tools/lang/formats.mjs from ICU 78.3 (CLDR 48.0). Do not edit:
  run the script again, and tests/vectors/formats.txt comes with it.

  A pattern is literals as ICU writes them and a (*token*) in braces for
  each field: yyyy yy M MM MMMM d dd H HH h hh K KK mm ss a. A months
  list is the twelve names that style writes, joined with |, and empty
  when its month is a number. }
unit Askr.Core.LangData;

{$mode Delphi}{$H+}

interface

type
  TLocaleFormat = record
    Tag: string;
    Decimal, Group, Minus: string;
    MinGrouping: Integer;
    DateShort, DateMedium, DateLong: string;
    DateTimeShort, DateTimeMedium, DateTimeLong: string;
    TimeShort, TimeMedium: string;
    MonthsShort, MonthsMedium, MonthsLong: string;
    DayPeriods: string;   { 24 words, one per hour, joined with | }
  end;

const
  LocaleFormats: array[0..58] of TLocaleFormat = (
    (Tag: 'en';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{M}/{d}/{yy}'; DateMedium: '{MMMM} {d}, {yyyy}'; DateLong: '{MMMM} {d}, {yyyy}';
     DateTimeShort: '{M}/{d}/{yy}, {h}:{mm} {a}'; DateTimeMedium: '{MMMM} {d}, {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{MMMM} {d}, {yyyy} at {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec';
     MonthsLong: 'January|February|March|April|May|June|July|August|September|October|November|December';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'en-GB';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} at {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sept|Oct|Nov|Dec';
     MonthsLong: 'January|February|March|April|May|June|July|August|September|October|November|December';
     DayPeriods: 'am|am|am|am|am|am|am|am|am|am|am|am|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm'),
    (Tag: 'en-AU';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}/{M}/{yy}, {h}:{mm} {a}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{d} {MMMM} {yyyy} at {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mar|Apr|May|June|July|Aug|Sept|Oct|Nov|Dec';
     MonthsLong: 'January|February|March|April|May|June|July|August|September|October|November|December';
     DayPeriods: 'am|am|am|am|am|am|am|am|am|am|am|am|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm'),
    (Tag: 'en-CA';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yyyy}-{MM}-{dd}'; DateMedium: '{MMMM} {d}, {yyyy}'; DateLong: '{MMMM} {d}, {yyyy}';
     DateTimeShort: '{yyyy}-{MM}-{dd}, {h}:{mm} {a}'; DateTimeMedium: '{MMMM} {d}, {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{MMMM} {d}, {yyyy} at {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec';
     MonthsLong: 'January|February|March|April|May|June|July|August|September|October|November|December';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'nb';
     Decimal: ','; Group: ' '; Minus: '−';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yyyy}'; DateMedium: '{d}. {MMMM} {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} kl. {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|feb.|mars|apr.|mai|juni|juli|aug.|sep.|okt.|nov.|des.';
     MonthsLong: 'januar|februar|mars|april|mai|juni|juli|august|september|oktober|november|desember';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'nn';
     Decimal: ','; Group: ' '; Minus: '−';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yyyy}'; DateMedium: '{d}. {MMMM} {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} kl. {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|feb.|mars|apr.|mai|juni|juli|aug.|sep.|okt.|nov.|des.';
     MonthsLong: 'januar|februar|mars|april|mai|juni|juli|august|september|oktober|november|desember';
     DayPeriods: 'f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|f.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.|e.m.'),
    (Tag: 'da';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yyyy}'; DateMedium: '{d}. {MMMM} {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yyyy}, {HH}.{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}, {HH}.{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} kl. {HH}.{mm}';
     TimeShort: '{HH}.{mm}'; TimeMedium: '{HH}.{mm}.{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|feb.|mar.|apr.|maj|jun.|jul.|aug.|sep.|okt.|nov.|dec.';
     MonthsLong: 'januar|februar|marts|april|maj|juni|juli|august|september|oktober|november|december';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'sv';
     Decimal: ','; Group: ' '; Minus: '−';
     MinGrouping: 1;
     DateShort: '{yyyy}-{MM}-{dd}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{yyyy}-{MM}-{dd} {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy} {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} kl. {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|feb.|mars|apr.|maj|juni|juli|aug.|sep.|okt.|nov.|dec.';
     MonthsLong: 'januari|februari|mars|april|maj|juni|juli|augusti|september|oktober|november|december';
     DayPeriods: 'fm|fm|fm|fm|fm|fm|fm|fm|fm|fm|fm|fm|em|em|em|em|em|em|em|em|em|em|em|em'),
    (Tag: 'de';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{dd}.{MM}.{yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} um {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'de-AT';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{dd}.{MM}.{yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} um {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'Jänner|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'de-CH';
     Decimal: '.'; Group: ''''; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{dd}.{MM}.{yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} um {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'nl';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}-{MM}-{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}-{MM}-{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} om {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan|feb|mrt|apr|mei|jun|jul|aug|sep|okt|nov|dec';
     MonthsLong: 'januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'fi';
     Decimal: ','; Group: ' '; Minus: '−';
     MinGrouping: 1;
     DateShort: '{d}.{M}.{yyyy}'; DateMedium: '{d}.{M}.{yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{d}.{M}.{yyyy} klo {H}.{mm}'; DateTimeMedium: '{d}.{M}.{yyyy} klo {H}.{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} klo {H}.{mm}';
     TimeShort: '{H}.{mm}'; TimeMedium: '{H}.{mm}.{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'tammikuuta|helmikuuta|maaliskuuta|huhtikuuta|toukokuuta|kesäkuuta|heinäkuuta|elokuuta|syyskuuta|lokakuuta|marraskuuta|joulukuuta';
     DayPeriods: 'ap.|ap.|ap.|ap.|ap.|ap.|ap.|ap.|ap.|ap.|ap.|ap.|ip.|ip.|ip.|ip.|ip.|ip.|ip.|ip.|ip.|ip.|ip.|ip.'),
    (Tag: 'et';
     Decimal: ','; Group: ' '; Minus: '−';
     MinGrouping: 2;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{d}. {MMMM} {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy}, kell {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jaan|veebr|märts|apr|mai|juuni|juuli|aug|sept|okt|nov|dets';
     MonthsLong: 'jaanuar|veebruar|märts|aprill|mai|juuni|juuli|august|september|oktoober|november|detsember';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'el';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}/{M}/{yy}, {h}:{mm} {a}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{d} {MMMM} {yyyy} στις {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'Ιαν|Φεβ|Μαρ|Απρ|Μαΐ|Ιουν|Ιουλ|Αυγ|Σεπ|Οκτ|Νοε|Δεκ';
     MonthsLong: 'Ιανουαρίου|Φεβρουαρίου|Μαρτίου|Απριλίου|Μαΐου|Ιουνίου|Ιουλίου|Αυγούστου|Σεπτεμβρίου|Οκτωβρίου|Νοεμβρίου|Δεκεμβρίου';
     DayPeriods: 'π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|π.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.|μ.μ.'),
    (Tag: 'hu';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{yyyy}. {MM}. {dd}.'; DateMedium: '{yyyy}. {MMMM} {d}.'; DateLong: '{yyyy}. {MMMM} {d}.';
     DateTimeShort: '{yyyy}. {MM}. {dd}. {H}:{mm}'; DateTimeMedium: '{yyyy}. {MMMM} {d}. {H}:{mm}'; DateTimeLong: '{yyyy}. {MMMM} {d}. {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|febr.|márc.|ápr.|máj.|jún.|júl.|aug.|szept.|okt.|nov.|dec.';
     MonthsLong: 'január|február|március|április|május|június|július|augusztus|szeptember|október|november|december';
     DayPeriods: 'de.|de.|de.|de.|de.|de.|de.|de.|de.|de.|de.|de.|du.|du.|du.|du.|du.|du.|du.|du.|du.|du.|du.|du.'),
    (Tag: 'tr';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}.{MM}.{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}.{MM}.{yyyy} {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy} {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'Oca|Şub|Mar|Nis|May|Haz|Tem|Ağu|Eyl|Eki|Kas|Ara';
     MonthsLong: 'Ocak|Şubat|Mart|Nisan|Mayıs|Haziran|Temmuz|Ağustos|Eylül|Ekim|Kasım|Aralık';
     DayPeriods: 'ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖÖ|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS|ÖS'),
    (Tag: 'bg';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{d}.{MM}.{yy} г.'; DateMedium: '{d}.{MM}.{yyyy} г.'; DateLong: '{d} {MMMM} {yyyy} г.';
     DateTimeShort: '{d}.{MM}.{yy} г., {H}:{mm}'; DateTimeMedium: '{d}.{MM}.{yyyy} г., {H}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} г. в {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'януари|февруари|март|април|май|юни|юли|август|септември|октомври|ноември|декември';
     DayPeriods: 'am|am|am|am|am|am|am|am|am|am|am|am|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm|pm'),
    (Tag: 'af';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yyyy}-{MM}-{dd}'; DateMedium: '{dd} {MMMM} {yyyy}'; DateLong: '{dd} {MMMM} {yyyy}';
     DateTimeShort: '{yyyy}-{MM}-{dd} {HH}:{mm}'; DateTimeMedium: '{dd} {MMMM} {yyyy} {HH}:{mm}'; DateTimeLong: '{dd} {MMMM} {yyyy} om {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'Jan.|Feb.|Mrt.|Apr.|Mei|Jun.|Jul.|Aug.|Sep.|Okt.|Nov.|Des.';
     MonthsLong: 'Januarie|Februarie|Maart|April|Mei|Junie|Julie|Augustus|September|Oktober|November|Desember';
     DayPeriods: 'vm.|vm.|vm.|vm.|vm.|vm.|vm.|vm.|vm.|vm.|vm.|vm.|nm.|nm.|nm.|nm.|nm.|nm.|nm.|nm.|nm.|nm.|nm.|nm.'),
    (Tag: 'sq';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{d}.{M}.{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}.{M}.{yy}, {h}:{mm} {a}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{d} {MMMM} {yyyy} në {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'jan|shk|mar|pri|maj|qer|korr|gush|sht|tet|nën|dhj';
     MonthsLong: 'janar|shkurt|mars|prill|maj|qershor|korrik|gusht|shtator|tetor|nëntor|dhjetor';
     DayPeriods: 'p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|p.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.|m.d.'),
    (Tag: 'eu';
     Decimal: ','; Group: '.'; Minus: '−';
     MinGrouping: 1;
     DateShort: '{yy}/{M}/{d}'; DateMedium: '{yyyy}(e)ko {MMMM} {d}(a)'; DateLong: '{yyyy}(e)ko {MMMM}ren {d}(a)';
     DateTimeShort: '{yy}/{M}/{d} ({HH}:{mm})'; DateTimeMedium: '{yyyy}(e)ko {MMMM} {d}(a) ({HH}:{mm})'; DateTimeLong: '{yyyy}(e)ko {MMMM}ren {d}(a) ({HH}:{mm})';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'urt.|ots.|mar.|api.|mai.|eka.|uzt.|abu.|ira.|urr.|aza.|abe.';
     MonthsLong: 'urtarrila|otsaila|martxoa|apirila|maiatza|ekaina|uztaila|abuztua|iraila|urria|azaroa|abendua';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'gl';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yy}'; DateMedium: '{d} de {MMMM} de {yyyy}'; DateLong: '{d} de {MMMM} de {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yy}, {HH}:{mm}'; DateTimeMedium: '{d} de {MMMM} de {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} de {MMMM} de {yyyy}, {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'xan.|feb.|mar.|abr.|maio|xuño|xul.|ago.|set.|out.|nov.|dec.';
     MonthsLong: 'xaneiro|febreiro|marzo|abril|maio|xuño|xullo|agosto|setembro|outubro|novembro|decembro';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'ka';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{d} {MMMM}. {yyyy}'; DateLong: '{d} {MMMM}, {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM}. {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM}, {yyyy}, {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'იან|თებ|მარ|აპრ|მაი|ივნ|ივლ|აგვ|სექ|ოქტ|ნოე|დეკ';
     MonthsLong: 'იანვარი|თებერვალი|მარტი|აპრილი|მაისი|ივნისი|ივლისი|აგვისტო|სექტემბერი|ოქტომბერი|ნოემბერი|დეკემბერი';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'az';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy}/{HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'yan|fev|mar|apr|may|iyn|iyl|avq|sen|okt|noy|dek';
     MonthsLong: 'yanvar|fevral|mart|aprel|may|iyun|iyul|avqust|sentyabr|oktyabr|noyabr|dekabr';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'kk';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{yyyy} ж. {dd} {MMMM}'; DateLong: '{yyyy} ж. {d} {MMMM}';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{yyyy} ж. {dd} {MMMM}, {HH}:{mm}'; DateTimeLong: '{yyyy} ж. {d} {MMMM}, {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'қаң.|ақп.|нау.|сәу.|мам.|мау.|шіл.|там.|қыр.|қаз.|қар.|жел.';
     MonthsLong: 'қаңтар|ақпан|наурыз|сәуір|мамыр|маусым|шілде|тамыз|қыркүйек|қазан|қараша|желтоқсан';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'ur';
     Decimal: '.'; Group: ','; Minus: '‎-';
     MinGrouping: 1;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM}، {yyyy}'; DateLong: '{d} {MMMM}، {yyyy}';
     DateTimeShort: '{d}/{M}/{yy}، {h}:{mm} {a}'; DateTimeMedium: '{d} {MMMM}، {yyyy}، {h}:{mm} {a}'; DateTimeLong: '{d} {MMMM}، {yyyy} کو {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'جنوری|فروری|مارچ|اپریل|مئی|جون|جولائی|اگست|ستمبر|اکتوبر|نومبر|دسمبر';
     MonthsLong: 'جنوری|فروری|مارچ|اپریل|مئی|جون|جولائی|اگست|ستمبر|اکتوبر|نومبر|دسمبر';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'sw';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy}, {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mac|Apr|Mei|Jun|Jul|Ago|Sep|Okt|Nov|Des';
     MonthsLong: 'Januari|Februari|Machi|Aprili|Mei|Juni|Julai|Agosti|Septemba|Oktoba|Novemba|Desemba';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'fr';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yyyy} {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} à {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'janv.|févr.|mars|avr.|mai|juin|juil.|août|sept.|oct.|nov.|déc.';
     MonthsLong: 'janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'fr-CA';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yyyy}-{MM}-{dd}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{yyyy}-{MM}-{dd} {HH} h {mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH} h {mm}'; DateTimeLong: '{d} {MMMM} {yyyy} à {HH} h {mm}';
     TimeShort: '{HH} h {mm}'; TimeMedium: '{HH} h {mm} min {ss} s';
     MonthsShort: '';
     MonthsMedium: 'janv.|févr.|mars|avr.|mai|juin|juill.|août|sept.|oct.|nov.|déc.';
     MonthsLong: 'janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'fr-CH';
     Decimal: ','; Group: ''''; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy} {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} à {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'janv.|févr.|mars|avr.|mai|juin|juil.|août|sept.|oct.|nov.|déc.';
     MonthsLong: 'janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'pt';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yyyy}'; DateMedium: '{d} de {MMMM} de {yyyy}'; DateLong: '{d} de {MMMM} de {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} de {MMMM} de {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} de {MMMM} de {yyyy} às {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|fev.|mar.|abr.|mai.|jun.|jul.|ago.|set.|out.|nov.|dez.';
     MonthsLong: 'janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'pt-PT';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{dd}/{MM}/{yy}'; DateMedium: '{dd}/{MM}/{yyyy}'; DateLong: '{d} de {MMMM} de {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yy}, {HH}:{mm}'; DateTimeMedium: '{dd}/{MM}/{yyyy}, {HH}:{mm}'; DateTimeLong: '{d} de {MMMM} de {yyyy} às {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'es';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 2;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} de {MMMM} de {yyyy}';
     DateTimeShort: '{d}/{M}/{yy}, {H}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {H}:{mm}'; DateTimeLong: '{d} de {MMMM} de {yyyy} a las {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'ene|feb|mar|abr|may|jun|jul|ago|sept|oct|nov|dic';
     MonthsLong: 'enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre';
     DayPeriods: 'a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.'),
    (Tag: 'es-MX';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} de {MMMM} de {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yy}, {h}:{mm} {a}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{d} de {MMMM} de {yyyy} a las {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic';
     MonthsLong: 'enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'it';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 2;
     DateShort: '{dd}/{MM}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} alle ore {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'gen|feb|mar|apr|mag|giu|lug|ago|set|ott|nov|dic';
     MonthsLong: 'gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'ca';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} del {yyyy}';
     DateTimeShort: '{d}/{M}/{yy} {H}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {H}:{mm}'; DateTimeLong: '{d} {MMMM} del {yyyy}, a les {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'de gen.|de febr.|de març|d’abr.|de maig|de juny|de jul.|d’ag.|de set.|d’oct.|de nov.|de des.';
     MonthsLong: 'de gener|de febrer|de març|d’abril|de maig|de juny|de juliol|d’agost|de setembre|d’octubre|de novembre|de desembre';
     DayPeriods: 'a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.'),
    (Tag: 'pl';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{d}.{MM}.{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'sty|lut|mar|kwi|maj|cze|lip|sie|wrz|paź|lis|gru';
     MonthsLong: 'stycznia|lutego|marca|kwietnia|maja|czerwca|lipca|sierpnia|września|października|listopada|grudnia';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'ru';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yyyy}'; DateMedium: '{d} {MMMM} {yyyy} г.'; DateLong: '{d} {MMMM} {yyyy} г.';
     DateTimeShort: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy} г., {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} г. в {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'янв.|февр.|мар.|апр.|мая|июн.|июл.|авг.|сент.|окт.|нояб.|дек.';
     MonthsLong: 'января|февраля|марта|апреля|мая|июня|июля|августа|сентября|октября|ноября|декабря';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'uk';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{d} {MMMM} {yyyy} р.'; DateLong: '{d} {MMMM} {yyyy} р.';
     DateTimeShort: '{dd}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy} р., {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} р. о {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'січ.|лют.|бер.|квіт.|трав.|черв.|лип.|серп.|вер.|жовт.|лист.|груд.';
     MonthsLong: 'січня|лютого|березня|квітня|травня|червня|липня|серпня|вересня|жовтня|листопада|грудня';
     DayPeriods: 'дп|дп|дп|дп|дп|дп|дп|дп|дп|дп|дп|дп|пп|пп|пп|пп|пп|пп|пп|пп|пп|пп|пп|пп'),
    (Tag: 'be';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{d}.{MM}.{yy}'; DateMedium: '{d} {MMMM} {yyyy} г.'; DateLong: '{d} {MMMM} {yyyy} г.';
     DateTimeShort: '{d}.{MM}.{yy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy} г., {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} г. у {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'сту|лют|сак|кра|мая|чэр|ліп|жні|вер|кас|ліс|сне';
     MonthsLong: 'студзеня|лютага|сакавіка|красавіка|мая|чэрвеня|ліпеня|жніўня|верасня|кастрычніка|лістапада|снежня';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'cs';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{d}. {M}. {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yy} {H}:{mm}'; DateTimeMedium: '{d}. {M}. {yyyy} {H}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} v {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'ledna|února|března|dubna|května|června|července|srpna|září|října|listopadu|prosince';
     DayPeriods: 'dop.|dop.|dop.|dop.|dop.|dop.|dop.|dop.|dop.|dop.|dop.|dop.|odp.|odp.|odp.|odp.|odp.|odp.|odp.|odp.|odp.|odp.|odp.|odp.'),
    (Tag: 'sk';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}. {M}. {yyyy}'; DateMedium: '{d}. {M}. {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{d}. {M}. {yyyy} {H}:{mm}'; DateTimeMedium: '{d}. {M}. {yyyy}, {H}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} o {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'januára|februára|marca|apríla|mája|júna|júla|augusta|septembra|októbra|novembra|decembra';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'hr';
     Decimal: ','; Group: '.'; Minus: '−';
     MinGrouping: 1;
     DateShort: '{dd}. {MM}. {yyyy}.'; DateMedium: '{d}. {MMMM} {yyyy}.'; DateLong: '{d}. {MMMM} {yyyy}.';
     DateTimeShort: '{dd}. {MM}. {yyyy}. {HH}:{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}. {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy}. u {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'sij|velj|ožu|tra|svi|lip|srp|kol|ruj|lis|stu|pro';
     MonthsLong: 'siječnja|veljače|ožujka|travnja|svibnja|lipnja|srpnja|kolovoza|rujna|listopada|studenoga|prosinca';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'sr';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}. {M}. {yyyy}.'; DateMedium: '{d}. {M}. {yyyy}.'; DateLong: '{d}. {MMMM} {yyyy}.';
     DateTimeShort: '{d}. {M}. {yyyy}. {HH}:{mm}'; DateTimeMedium: '{d}. {M}. {yyyy}. {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy}. {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'јануар|фебруар|март|април|мај|јун|јул|август|септембар|октобар|новембар|децембар';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'bs';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}. {M}. {yyyy}.'; DateMedium: '{d}. {MMMM} {yyyy}.'; DateLong: '{d}. {MMMM} {yyyy}.';
     DateTimeShort: '{d}. {M}. {yyyy}. u {HH}:{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}. u {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy}. u {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan|feb|mar|apr|maj|jun|jul|aug|sep|okt|nov|dec';
     MonthsLong: 'januar|februar|mart|april|maj|juni|juli|august|septembar|oktobar|novembar|decembar';
     DayPeriods: 'a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|a. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.|p. m.'),
    (Tag: 'ro';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}.{MM}.{yyyy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}.{MM}.{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} la {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'ian.|feb.|mar.|apr.|mai|iun.|iul.|aug.|sept.|oct.|nov.|dec.';
     MonthsLong: 'ianuarie|februarie|martie|aprilie|mai|iunie|iulie|august|septembrie|octombrie|noiembrie|decembrie';
     DayPeriods: 'a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|a.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.|p.m.'),
    (Tag: 'lt';
     Decimal: ','; Group: ' '; Minus: '−';
     MinGrouping: 1;
     DateShort: '{yyyy}-{MM}-{dd}'; DateMedium: '{yyyy}-{MM}-{dd}'; DateLong: '{yyyy} m. {MMMM} {d} d.';
     DateTimeShort: '{yyyy}-{MM}-{dd} {HH}:{mm}'; DateTimeMedium: '{yyyy}-{MM}-{dd} {HH}:{mm}'; DateTimeLong: '{yyyy} m. {MMMM} {d} d. {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'sausio|vasario|kovo|balandžio|gegužės|birželio|liepos|rugpjūčio|rugsėjo|spalio|lapkričio|gruodžio';
     DayPeriods: 'priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|priešpiet|popiet|popiet|popiet|popiet|popiet|popiet|popiet|popiet|popiet|popiet|popiet|popiet'),
    (Tag: 'lv';
     Decimal: ','; Group: ' '; Minus: '-';
     MinGrouping: 2;
     DateShort: '{dd}.{MM}.{yy}'; DateMedium: '{yyyy}. gada {d}. {MMMM}'; DateLong: '{yyyy}. gada {d}. {MMMM}';
     DateTimeShort: '{dd}.{MM}.{yy} {HH}:{mm}'; DateTimeMedium: '{yyyy}. gada {d}. {MMMM} {HH}:{mm}'; DateTimeLong: '{yyyy}. gada {d}. {MMMM} {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'janv.|febr.|marts|apr.|maijs|jūn.|jūl.|aug.|sept.|okt.|nov.|dec.';
     MonthsLong: 'janvāris|februāris|marts|aprīlis|maijs|jūnijs|jūlijs|augusts|septembris|oktobris|novembris|decembris';
     DayPeriods: 'priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|priekšp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.|pēcp.'),
    (Tag: 'ar';
     Decimal: '.'; Group: ','; Minus: '‎-';
     MinGrouping: 1;
     DateShort: '{d}‏/{M}‏/{yyyy}'; DateMedium: '{dd}‏/{MM}‏/{yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}‏/{M}‏/{yyyy}، {h}:{mm} {a}'; DateTimeMedium: '{dd}‏/{MM}‏/{yyyy}، {h}:{mm} {a}'; DateTimeLong: '{d} {MMMM} {yyyy} في {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: 'يناير|فبراير|مارس|أبريل|مايو|يونيو|يوليو|أغسطس|سبتمبر|أكتوبر|نوفمبر|ديسمبر';
     DayPeriods: 'ص|ص|ص|ص|ص|ص|ص|ص|ص|ص|ص|ص|م|م|م|م|م|م|م|م|م|م|م|م'),
    (Tag: 'he';
     Decimal: '.'; Group: ','; Minus: '‎-';
     MinGrouping: 1;
     DateShort: '{d}.{M}.{yyyy}'; DateMedium: '{d} ב{MMMM} {yyyy}'; DateLong: '{d} ב{MMMM} {yyyy}';
     DateTimeShort: '{d}.{M}.{yyyy}, {H}:{mm}'; DateTimeMedium: '{d} ב{MMMM} {yyyy}, {H}:{mm}'; DateTimeLong: '{d} ב{MMMM} {yyyy} בשעה {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'ינו׳|פבר׳|מרץ|אפר׳|מאי|יוני|יולי|אוג׳|ספט׳|אוק׳|נוב׳|דצמ׳';
     MonthsLong: 'ינואר|פברואר|מרץ|אפריל|מאי|יוני|יולי|אוגוסט|ספטמבר|אוקטובר|נובמבר|דצמבר';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'is';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}.{M}.{yyyy}'; DateMedium: '{d}. {MMMM} {yyyy}'; DateLong: '{d}. {MMMM} {yyyy}';
     DateTimeShort: '{d}.{M}.{yyyy}, {HH}:{mm}'; DateTimeMedium: '{d}. {MMMM} {yyyy}, {HH}:{mm}'; DateTimeLong: '{d}. {MMMM} {yyyy} kl. {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'jan.|feb.|mar.|apr.|maí|jún.|júl.|ágú.|sep.|okt.|nóv.|des.';
     MonthsLong: 'janúar|febrúar|mars|apríl|maí|júní|júlí|ágúst|september|október|nóvember|desember';
     DayPeriods: 'f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|f.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.|e.h.'),
    (Tag: 'ja';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yyyy}/{MM}/{dd}'; DateMedium: '{yyyy}/{MM}/{dd}'; DateLong: '{yyyy}年{M}月{d}日';
     DateTimeShort: '{yyyy}/{MM}/{dd} {H}:{mm}'; DateTimeMedium: '{yyyy}/{MM}/{dd} {H}:{mm}'; DateTimeLong: '{yyyy}年{M}月{d}日 {H}:{mm}';
     TimeShort: '{H}:{mm}'; TimeMedium: '{H}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: '';
     DayPeriods: '午前|午前|午前|午前|午前|午前|午前|午前|午前|午前|午前|午前|午後|午後|午後|午後|午後|午後|午後|午後|午後|午後|午後|午後'),
    (Tag: 'zh';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yyyy}/{M}/{d}'; DateMedium: '{yyyy}年{M}月{d}日'; DateLong: '{yyyy}年{M}月{d}日';
     DateTimeShort: '{yyyy}/{M}/{d} {HH}:{mm}'; DateTimeMedium: '{yyyy}年{M}月{d}日 {HH}:{mm}'; DateTimeLong: '{yyyy}年{M}月{d}日 {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: '';
     DayPeriods: '上午|上午|上午|上午|上午|上午|上午|上午|上午|上午|上午|上午|下午|下午|下午|下午|下午|下午|下午|下午|下午|下午|下午|下午'),
    (Tag: 'zh-TW';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yyyy}/{M}/{d}'; DateMedium: '{yyyy}年{M}月{d}日'; DateLong: '{yyyy}年{M}月{d}日';
     DateTimeShort: '{yyyy}/{M}/{d} {a}{h}:{mm}'; DateTimeMedium: '{yyyy}年{M}月{d}日 {a}{h}:{mm}'; DateTimeLong: '{yyyy}年{M}月{d}日 {a}{h}:{mm}';
     TimeShort: '{a}{h}:{mm}'; TimeMedium: '{a}{h}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: '';
     DayPeriods: '凌晨|凌晨|凌晨|凌晨|凌晨|清晨|清晨|清晨|上午|上午|上午|上午|中午|下午|下午|下午|下午|下午|下午|晚上|晚上|晚上|晚上|晚上'),
    (Tag: 'ko';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{yy}. {M}. {d}.'; DateMedium: '{yyyy}. {M}. {d}.'; DateLong: '{yyyy}년 {MMMM} {d}일';
     DateTimeShort: '{yy}. {M}. {d}. {a} {h}:{mm}'; DateTimeMedium: '{yyyy}. {M}. {d}. {a} {h}:{mm}'; DateTimeLong: '{yyyy}년 {MMMM} {d}일 {a} {h}:{mm}';
     TimeShort: '{a} {h}:{mm}'; TimeMedium: '{a} {h}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: '';
     MonthsLong: '1월|2월|3월|4월|5월|6월|7월|8월|9월|10월|11월|12월';
     DayPeriods: '오전|오전|오전|오전|오전|오전|오전|오전|오전|오전|오전|오전|오후|오후|오후|오후|오후|오후|오후|오후|오후|오후|오후|오후'),
    (Tag: 'th';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} ค.ศ. {yyyy}';
     DateTimeShort: '{d}/{M}/{yy} {HH}:{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy} {HH}:{mm}'; DateTimeLong: '{d} {MMMM} ค.ศ. {yyyy} เวลา {HH}:{mm}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'ม.ค.|ก.พ.|มี.ค.|เม.ย.|พ.ค.|มิ.ย.|ก.ค.|ส.ค.|ก.ย.|ต.ค.|พ.ย.|ธ.ค.';
     MonthsLong: 'มกราคม|กุมภาพันธ์|มีนาคม|เมษายน|พฤษภาคม|มิถุนายน|กรกฎาคม|สิงหาคม|กันยายน|ตุลาคม|พฤศจิกายน|ธันวาคม';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'vi';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}/{M}/{yy}'; DateMedium: '{d} {MMMM}, {yyyy}'; DateLong: '{d} {MMMM}, {yyyy}';
     DateTimeShort: '{HH}:{mm} {d}/{M}/{yy}'; DateTimeMedium: '{HH}:{mm} {d} {MMMM}, {yyyy}'; DateTimeLong: 'lúc {HH}:{mm} {d} {MMMM}, {yyyy}';
     TimeShort: '{HH}:{mm}'; TimeMedium: '{HH}:{mm}:{ss}';
     MonthsShort: '';
     MonthsMedium: 'thg 1|thg 2|thg 3|thg 4|thg 5|thg 6|thg 7|thg 8|thg 9|thg 10|thg 11|thg 12';
     MonthsLong: 'tháng 1|tháng 2|tháng 3|tháng 4|tháng 5|tháng 6|tháng 7|tháng 8|tháng 9|tháng 10|tháng 11|tháng 12';
     DayPeriods: 'SA|SA|SA|SA|SA|SA|SA|SA|SA|SA|SA|SA|CH|CH|CH|CH|CH|CH|CH|CH|CH|CH|CH|CH'),
    (Tag: 'id';
     Decimal: ','; Group: '.'; Minus: '-';
     MinGrouping: 1;
     DateShort: '{dd}/{MM}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{dd}/{MM}/{yy}, {HH}.{mm}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {HH}.{mm}'; DateTimeLong: '{d} {MMMM} {yyyy} pukul {HH}.{mm}';
     TimeShort: '{HH}.{mm}'; TimeMedium: '{HH}.{mm}.{ss}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mar|Apr|Mei|Jun|Jul|Agu|Sep|Okt|Nov|Des';
     MonthsLong: 'Januari|Februari|Maret|April|Mei|Juni|Juli|Agustus|September|Oktober|November|Desember';
     DayPeriods: 'AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|AM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM|PM'),
    (Tag: 'ms';
     Decimal: '.'; Group: ','; Minus: '-';
     MinGrouping: 1;
     DateShort: '{d}/{MM}/{yy}'; DateMedium: '{d} {MMMM} {yyyy}'; DateLong: '{d} {MMMM} {yyyy}';
     DateTimeShort: '{d}/{MM}/{yy}, {h}:{mm} {a}'; DateTimeMedium: '{d} {MMMM} {yyyy}, {h}:{mm} {a}'; DateTimeLong: '{d} {MMMM} {yyyy} pada {h}:{mm} {a}';
     TimeShort: '{h}:{mm} {a}'; TimeMedium: '{h}:{mm}:{ss} {a}';
     MonthsShort: '';
     MonthsMedium: 'Jan|Feb|Mac|Apr|Mei|Jun|Jul|Ogo|Sep|Okt|Nov|Dis';
     MonthsLong: 'Januari|Februari|Mac|April|Mei|Jun|Julai|Ogos|September|Oktober|November|Disember';
     DayPeriods: 'PG|PG|PG|PG|PG|PG|PG|PG|PG|PG|PG|PG|PTG|PTG|PTG|PTG|PTG|PTG|PTG|PTG|PTG|PTG|PTG|PTG')
  );

implementation

end.
